apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pg-config
spec:
  type: configuration.postgresql
  version: v1
  metadata:
    # Connection string
    - name: connectionString
      value: "host=localhost user=postgres password=DaprPostgresPassword port=5432 connect_timeout=10 database=postgres"
    # Name of the table which holds configuration information
    - name: table
      value: "configtable" 
