apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: state-store-2
spec:
  type: state.postgresql
  version: v2
  metadata:
    - name: connectionString
      value: "host=localhost user=postgres password=DaprPostgresPassword port=5432 connect_timeout=10 database=statestoredb"

