apiVersion: v1
kind: Secret
metadata:
  name: aspire-postgres-secret
type: Opaque
data:
  postgres-password: QXNwMXIzUEBzc3cwcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: aspire-mongo-secret
type: Opaque
data:
  mongo-password: QXNwMXIzUEBzc3cwcmQ=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "aspiredb"
            - name: POSTGRES_USER
              value: "aspireuser"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aspire-postgres-secret
                  key: postgres-password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0.4
          ports:
            - containerPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: postgres-0



---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: mongo-0


---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: redis-0
