---
apiVersion: v1
kind: Service
metadata:
  name: microservice01
  labels: 
    app: microservice01
spec:
  type: ClusterIP
  selector:
    app: microservice01
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8443
